version: '3.7'

x-logging: &logging
  logging:
    options:
      max-size: "200k"
      max-file: "1"

services:
  cron:
    <<: *logging
    image: ghcr.io/ftpcory/docker-wordpress:cron
    command: ["cron", "-f"]
    depends_on:
      - web
    volumes:
      - wordpress:/app

  db:
    <<: *logging
    image  : mariadb:10.4
    restart: unless-stopped
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
    volumes:
      - db-data:/var/lib/mysql

  web:
    <<: *logging
    image : ghcr.io/ftpcory/docker-wordpress:web
    restart: unless-stopped
    working_dir: /var/www/html
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 2
    expose:
      - 80

  redis:
    <<: *logging
    image: redis
    expose:
      - 6379
    restart: unless-stopped

volumes:
  db-data:
  wordpress:
